### ISSUE TITLE
viewer lists KOIs that are not present

### ISSUE THREAD

**Issue by petigura** [pentrican10/alderaan-viewer#25]
It would be good to remove the entries where the files do not exist. 

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/c04d4349-28af-4c59-b001-4719cb4c7376">

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/4d3fa31b-d837-4d74-82dc-12e7b2808d83">

**Comment by pentrican10** [comment]
This should be fixed now! The table will show koi_id rows that correspond with the koi_ids in the data_directory. If any show errors in loading plot, or 'data not found', it now most likely means the pipeline failed for that KOI. (there is a folder in the data_directory with no data in it)
