### ISSUE TITLE
App crashes if unexpected files are in Results folder

### ISSUE THREAD

**Issue by gjgilbert** [pentrican10/alderaan-viewer#30]
The following error arises if non-directory files are in the Results folder

> NotADirectoryError: [Errno 20] Not a directory: '/Users/research/projects/alderaan/Results/.DS_Store/.DS_Store.csv'

**Comment by pentrican10** [comment]
It now checks for only directory files with a corresponding csv table inside.

**Comment by gjgilbert** [comment]
@pentrican10 I'm still getting this error. You may need to specifically check for hidden files as well. Ping me when you've pushed an update and I can test this on my machine.

**Comment by pentrican10** [comment]
I pushed an update to the development branch to handle hidden files!
